// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"
	formula "math-parser/internal/math/domain/formula"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id formula.ID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, formula.ID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id formula.ID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id formula.ID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(formula.ID))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, formula.ID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockRepository) Get(ctx context.Context, id formula.ID) (*formula.Equation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *formula.Equation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, formula.ID) (*formula.Equation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, formula.ID) *formula.Equation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*formula.Equation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, formula.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id formula.ID
func (_e *MockRepository_Expecter) Get(ctx interface{}, id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, id formula.ID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(formula.ID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 *formula.Equation, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, formula.ID) (*formula.Equation, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetFromValue provides a mock function with given fields: ctx, value
func (_m *MockRepository) GetFromValue(ctx context.Context, value string) (*formula.Equation, error) {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for GetFromValue")
	}

	var r0 *formula.Equation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*formula.Equation, error)); ok {
		return rf(ctx, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *formula.Equation); ok {
		r0 = rf(ctx, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*formula.Equation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetFromValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFromValue'
type MockRepository_GetFromValue_Call struct {
	*mock.Call
}

// GetFromValue is a helper method to define mock.On call
//   - ctx context.Context
//   - value string
func (_e *MockRepository_Expecter) GetFromValue(ctx interface{}, value interface{}) *MockRepository_GetFromValue_Call {
	return &MockRepository_GetFromValue_Call{Call: _e.mock.On("GetFromValue", ctx, value)}
}

func (_c *MockRepository_GetFromValue_Call) Run(run func(ctx context.Context, value string)) *MockRepository_GetFromValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetFromValue_Call) Return(_a0 *formula.Equation, _a1 error) *MockRepository_GetFromValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetFromValue_Call) RunAndReturn(run func(context.Context, string) (*formula.Equation, error)) *MockRepository_GetFromValue_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, equation
func (_m *MockRepository) Insert(ctx context.Context, equation *formula.Equation) (*formula.Equation, error) {
	ret := _m.Called(ctx, equation)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *formula.Equation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *formula.Equation) (*formula.Equation, error)); ok {
		return rf(ctx, equation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *formula.Equation) *formula.Equation); ok {
		r0 = rf(ctx, equation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*formula.Equation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *formula.Equation) error); ok {
		r1 = rf(ctx, equation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - equation *formula.Equation
func (_e *MockRepository_Expecter) Insert(ctx interface{}, equation interface{}) *MockRepository_Insert_Call {
	return &MockRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, equation)}
}

func (_c *MockRepository_Insert_Call) Run(run func(ctx context.Context, equation *formula.Equation)) *MockRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*formula.Equation))
	})
	return _c
}

func (_c *MockRepository_Insert_Call) Return(_a0 *formula.Equation, _a1 error) *MockRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Insert_Call) RunAndReturn(run func(context.Context, *formula.Equation) (*formula.Equation, error)) *MockRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRepository) List(ctx context.Context) ([]*formula.Equation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*formula.Equation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*formula.Equation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*formula.Equation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*formula.Equation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) List(ctx interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []*formula.Equation, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context) ([]*formula.Equation, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, equation
func (_m *MockRepository) Update(ctx context.Context, equation *formula.Equation) (*formula.Equation, error) {
	ret := _m.Called(ctx, equation)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *formula.Equation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *formula.Equation) (*formula.Equation, error)); ok {
		return rf(ctx, equation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *formula.Equation) *formula.Equation); ok {
		r0 = rf(ctx, equation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*formula.Equation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *formula.Equation) error); ok {
		r1 = rf(ctx, equation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - equation *formula.Equation
func (_e *MockRepository_Expecter) Update(ctx interface{}, equation interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, equation)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, equation *formula.Equation)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*formula.Equation))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 *formula.Equation, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, *formula.Equation) (*formula.Equation, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
