// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Equation struct {
	ID        int64
	Value     string
	Category  string
	Cause     pgtype.Text
	Effect    pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type EquationVariable struct {
	EquationID int64
	VariableID int64
}

type Variable struct {
	ID        int64
	Name      string
	Vcategory string
	Arguments []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
